[package]
name = "bindlocal-server"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.42"
tokio = { version = "1.0", features = ["full"] }

[dependencies.uuid]
version = "1.18.1"
features = [
    "v4",
]
