[package]
name = "connl-server"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.42"
rand = "0.9.2"
tokio = { version = "1.0", features = ["full"] }
tracing = "0.1"
tracing-subscriber = "0.3"
